#!/usr/bin/env bash
# Installs gerbidigm hooks and merge drivers into the local git repo.
# Run once after a fresh clone.

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_SRC="$REPO_ROOT/gerbidigm/hooks"
HOOKS_DST="$REPO_ROOT/.git/hooks"

for hook in "$HOOKS_SRC"/*; do
  name="$(basename "$hook")"
  ln -sf "$hook" "$HOOKS_DST/$name"
  echo "Installed hook: $name"
done

# Register the package-lock.json merge driver in local git config.
# This makes 'git rebase upstream/main' resolve package-lock.json conflicts
# automatically by taking upstream's version, then the post-rebase hook
# regenerates it with npm install to incorporate any gerbidigm additions.
git config merge.take-upstream-lockfile.name \
  "Take upstream package-lock.json; regenerated by post-rebase hook"
git config merge.take-upstream-lockfile.driver \
  "$REPO_ROOT/gerbidigm/merge-drivers/take-upstream-lockfile %O %A %B %P"
echo "Registered merge driver: take-upstream-lockfile"

echo "Done."
